### ISSUE TITLE
roadmap in sayit

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#471]
Is possible share a roadmap, what expected in sayit?

**Comment by dracos** [comment]
You can see from the open tickets the kinds of things that are asked for or wanted, and there is a huboard of them at https://huboard.com/mysociety/sayit which provides a loose sense of ordering to those. These can only be done as and when time is available, or if someone volunteers to add them, as people have done.

SayIt is a Django application component for storing speeches and statements. Having code to add comments to speeches is already provided by existing applications (e.g. Django's contrib comments app from https://github.com/django/django-contrib-comments, or whatever you would want to use in a different framework). It wouldn't really make sense for SayIt to handle commenting itself, because each user of SayIt might want to do it differently.
