### ISSUE TITLE
An exception of type DataError occurred, arguments: value too long for type character varying(50)

### ISSUE THREAD

**Issue by johnfelipe** [mysociety/sayit#479]
Hello when i upload my akoma ntoso in VPS godaddy, this is error show me:

       An exception of type DataError occurred, arguments:
       value too long for type character varying(50)

How i fix it?

**Comment by duncanparkes** [comment]
Hi @johnfelipe 

What's happened is fairly easy to see. There's something in your Akomo Ntoso which is longer than a 50 character maximum length on the database field it needs to go into. Did you get more of a traceback than this? If so, we might be able to work out which field it is and then you can try to make it shorter.

Cheers,

Duncan

**Comment by dracos** [comment]
Slugs have a maximum length of 50 characters; but setting a slug should set/crop it appropriately. As always, we don't have enough details.

**Comment by johnfelipe** [comment]
In my local enviroment dont show that error, yes, in VPS in godaddy.
@duncanparkes yes it show me 15 times

**Comment by johnfelipe** [comment]
Reinstall all in my VPS of Godaddy but same error, please tell me how increase that length, because is bad upload.

In my local:

![local](https://cloud.githubusercontent.com/assets/428820/7289136/6f6a4e0e-e931-11e4-963f-cb5cc1fbd9df.png)

In my Godaddy VPS:

![vps](https://cloud.githubusercontent.com/assets/428820/7289213/5ad26cf0-e932-11e4-9453-6dba67c53239.png)

27 sections less

**Comment by dracos** [comment]
So which import fails? Have you tried each file manually to find out which it is? When you have, what is different about that file? Does it have a speaker or a section with a really long name? What's the longest such speaker or section name?

What is the database encoding of your database on the server as opposed to locally? As it works locally for you, it seems plausible that the server encoding differs and is storing bytes rather than characters and thus is getting confused as to the limit. I can't think of anything else, but this appears to be a problem with the database, not with SayIt, given it works locally.

**Comment by johnfelipe** [comment]
solved: "On the production server they had ascii encoding while on the dev box it is utf-8. By default postgres creates a database using the template1. My understanding is that if its encoding is not utf-8, then the database you create will have this issue, even though you create it with utf-8 encoding."
Before create sayit database need do this:

	UPDATE pg_database SET datallowconn = TRUE where datname = 'template0';
	\c template0
	UPDATE pg_database SET datistemplate = FALSE where datname = 'template1';
	drop database template1;
	create database template1 with template = template0 encoding = 'UNICODE';
	UPDATE pg_database SET datistemplate = TRUE where datname = 'template1';
	\c template1
	UPDATE pg_database SET datallowconn = FALSE where datname = 'template0';

Later
CREATE DATABASE sayit
