### ISSUE TITLE
load templatetags from sub-app 

### ISSUE THREAD

**Issue by illucent** [mysociety/sayit#508]
Cannot load any eg. {% load speech_extras %} from example_project*/  templatetags/ folder

**Comment by dracos** [comment]
Just to check, by what you say I think you mean you've created a `templatetags` folder in your `example_project` directory, and files you add there aren't loadable in templates? Yes, this is the case – `templatetags` folders can only be used in apps, not projects, see https://docs.djangoproject.com/en/1.9/howto/custom-template-tags/ You should create a new app to store your custom template tags.

Or are you saying you've created a new app inside `example_project` with a `templatetags` directory in there? That should be okay, as long as the app is in your `INSTALLED_APPS`, though it might be clearer if the app is not installed underneath your project but alongside, that is how Django sets it up by default. There's certainly nothing in our code base that would prevent template tags from working if set up correctly.

You might well be already doing this, but just in case I do recommend if at all possible you use SayIt as an app within your own Django app or project, e.g. as explained at http://mysociety.github.io/sayit/install/#installing-sayit-as-a-django-app

**Comment by illucent** [comment]
not example_project, a new complex installation eg. structure:

virtualenv-sayit/ 
sayit.mysociety.org/
--- manage.py
--- sayit_mysociety_org/ <--- app
--------- templatetags/
--------- templatetags/ <---- templatetags from here
--------- models.py
--------- views.py

**Comment by dracos** [comment]
I am confused by your naming, sorry – if you have cloned https://github.com/mysociety/sayit.mysociety.org then the `sayit_mysociety_org` directory there is a Django project, not an app.

What error message do you receive? Have you tried importing the template tag library directly at the command line? e.g.
```
python manage.py shell
>>> from yourapp.templatetags import speech_extras
```
Does that work? Is your code on github somewhere?

**Comment by illucent** [comment]
whoops, project. thanks, not yet 'github'ed'

```
python manage.py shell
>>> from yourapp.templatetags import speech_extras
```
does not work

repo for this project https://github.com/illucent/sayit.dev.git

**Comment by dracos** [comment]
By "yourapp" (and the rest of that line) I meant for you to replace it with whatever the path is to your templatetag, of course. Though I believe from what you say that the issue is as I said and that you have tried to put a templatetag directory in a Django project, which will not work. This is nothing to do with SayIt, this is Django.
Committing an entire repository in one commit is probably not what you want to do; GitHub lets you fork repositories to work from which might be a better way for you to proceed.

**Comment by illucent** [comment]
```
from sayit.mysociety.org.templatetags import speech_extras
```
output:
```
from: can't read /var/mail/sayit.mysociety.org.templatetags
```

**Comment by dracos** [comment]
Firstly, that error means you ran that at a bash command line prompt, not a python shell, which is what you would get after the first command I gave you to run (hence the `>>>` quoted). `from` is a mail command, which is absolutely nothing to do with this issue.

Secondly, you can't have a python package called "sayit.mysociety.org", packages don't have dots in them. I imagine you might want `from sayit_mysociety_org.templatetags import speech_extras` but as I say it doesn't matter if that works or not, because the issue is as I have already stated - you cannot have templatetags in a Django project, only an app.
